# Generated by Django 4.0.3 on 2022-04-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='earned_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='needed_price',
            field=models.IntegerField(default=0),
        ),
    ]
