# Generated by Django 4.0.3 on 2022-04-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteering',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='email',
        ),
    ]
