# Generated by Django 4.0.3 on 2022-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_donation_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order_id',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
