# Generated by Django 4.0.3 on 2022-05-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_donation_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='order_id',
        ),
    ]
